# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  # ВАЖНО: Это шаблонный файл!
  # Перед установкой системы ОБЯЗАТЕЛЬНО замените на реальную конфигурацию:
  # sudo nixos-generate-config --root /mnt --dir .
  # или: sudo nixos-generate-config (если система уже установлена)

  # Boot loader configuration
  boot.initrd.availableKernelModules = [
    "ahci" "xhci_pci" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod"
    "nvme" "ata_piix" "usb_storage" "usbhid"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # ШАБЛОН файловых систем - ЗАМЕНИТЕ НА ВАШИ РЕАЛЬНЫЕ!
  # Получите UUID ваших разделов: lsblk -f или blkid
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/REPLACE-WITH-YOUR-ROOT-UUID";
    fsType = "ext4";
    # Для btrfs используйте:
    # fsType = "btrfs";
    # options = [ "subvol=root" "compress=zstd" "noatime" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/REPLACE-WITH-YOUR-BOOT-UUID";
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  # Swap partition (если есть)
  # swapDevices = [
  #   { device = "/dev/disk/by-uuid/REPLACE-WITH-YOUR-SWAP-UUID"; }
  # ];

  # Swap file (альтернатива swap разделу)
  # swapDevices = [
  #   {
  #     device = "/swapfile";
  #     size = 8192; # Размер в MB
  #   }
  # ];

  # Networking
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s3.useDHCP = lib.mkDefault true;

  # CPU Configuration
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  # Intel CPU specific
  # hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # AMD CPU specific
  # hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Hardware optimizations
  hardware.enableRedistributableFirmware = true;

  # Power management
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

  # Additional hardware support
  services.fwupd.enable = true; # Firmware updates
}
